[package]
name = "robutt"
version = "0.1.0"
authors = ["Erik Hollensbe <github@hollensbe.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irc = { version = ">=0", features = [ "yaml", "json", "toml" ] }
rand = ">=0"
futures = ">=0"
futures-util = '>=0'
tokio = { version = '0.2', features = [ 'full' ] }
regex = '>=0'
discord = { git = "https://github.com/SpaceManiac/discord-rs", branch = "master", features = [ ] }
anyhow = "1.0"
