/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};


/// struct for typed errors of method `developers`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DevelopersError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn developers(configuration: &configuration::Configuration, apikey: &str) -> Result<crate::models::Developers, Error<DevelopersError>> {

    let client = &configuration.client;

    let uri_str = format!("{}/v1/Developers", configuration.base_path);
    let mut req_builder = client.get(uri_str.as_str());

    req_builder = req_builder.query(&[("apikey", &apikey.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = client.execute(req).await?;

    let status = resp.status();
    let content = resp.text().await?;

    if status.is_success() {
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let entity: Option<DevelopersError> = serde_json::from_str(&content).ok();
        let error = ResponseContent { status, content, entity };
        Err(Error::ResponseError(error))
    }
}

