/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};


/// struct for typed errors of method `platforms`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlatformsError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method `platforms_by_platform_id`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlatformsByPlatformIdError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method `platforms_by_platform_name`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlatformsByPlatformNameError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method `platforms_images`
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PlatformsImagesError {
    Status400(),
    Status403(),
    UnknownValue(serde_json::Value),
}


pub async fn platforms(configuration: &configuration::Configuration, apikey: &str, fields: Option<&str>) -> Result<crate::models::Platforms, Error<PlatformsError>> {

    let client = &configuration.client;

    let uri_str = format!("{}/v1/Platforms", configuration.base_path);
    let mut req_builder = client.get(uri_str.as_str());

    req_builder = req_builder.query(&[("apikey", &apikey.to_string())]);
    if let Some(ref s) = fields {
        req_builder = req_builder.query(&[("fields", &s.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = client.execute(req).await?;

    let status = resp.status();
    let content = resp.text().await?;

    if status.is_success() {
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let entity: Option<PlatformsError> = serde_json::from_str(&content).ok();
        let error = ResponseContent { status, content, entity };
        Err(Error::ResponseError(error))
    }
}

pub async fn platforms_by_platform_id(configuration: &configuration::Configuration, apikey: &str, id: i32, fields: Option<&str>) -> Result<crate::models::PlatformsByPlatformId, Error<PlatformsByPlatformIdError>> {

    let client = &configuration.client;

    let uri_str = format!("{}/v1/Platforms/ByPlatformID", configuration.base_path);
    let mut req_builder = client.get(uri_str.as_str());

    req_builder = req_builder.query(&[("apikey", &apikey.to_string())]);
    req_builder = req_builder.query(&[("id", &id.to_string())]);
    if let Some(ref s) = fields {
        req_builder = req_builder.query(&[("fields", &s.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = client.execute(req).await?;

    let status = resp.status();
    let content = resp.text().await?;

    if status.is_success() {
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let entity: Option<PlatformsByPlatformIdError> = serde_json::from_str(&content).ok();
        let error = ResponseContent { status, content, entity };
        Err(Error::ResponseError(error))
    }
}

pub async fn platforms_by_platform_name(configuration: &configuration::Configuration, apikey: &str, name: &str, fields: Option<&str>) -> Result<crate::models::PlatformsByPlatformName, Error<PlatformsByPlatformNameError>> {

    let client = &configuration.client;

    let uri_str = format!("{}/v1/Platforms/ByPlatformName", configuration.base_path);
    let mut req_builder = client.get(uri_str.as_str());

    req_builder = req_builder.query(&[("apikey", &apikey.to_string())]);
    req_builder = req_builder.query(&[("name", &name.to_string())]);
    if let Some(ref s) = fields {
        req_builder = req_builder.query(&[("fields", &s.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = client.execute(req).await?;

    let status = resp.status();
    let content = resp.text().await?;

    if status.is_success() {
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let entity: Option<PlatformsByPlatformNameError> = serde_json::from_str(&content).ok();
        let error = ResponseContent { status, content, entity };
        Err(Error::ResponseError(error))
    }
}

/// results can be filtered with `filter[type]` param
pub async fn platforms_images(configuration: &configuration::Configuration, apikey: &str, platforms_id: &str, filter_type: Option<&str>, page: Option<i32>) -> Result<crate::models::PlatformsImages, Error<PlatformsImagesError>> {

    let client = &configuration.client;

    let uri_str = format!("{}/v1/Platforms/Images", configuration.base_path);
    let mut req_builder = client.get(uri_str.as_str());

    req_builder = req_builder.query(&[("apikey", &apikey.to_string())]);
    req_builder = req_builder.query(&[("platforms_id", &platforms_id.to_string())]);
    if let Some(ref s) = filter_type {
        req_builder = req_builder.query(&[("filter[type]", &s.to_string())]);
    }
    if let Some(ref s) = page {
        req_builder = req_builder.query(&[("page", &s.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = client.execute(req).await?;

    let status = resp.status();
    let content = resp.text().await?;

    if status.is_success() {
        serde_json::from_str(&content).map_err(Error::from)
    } else {
        let entity: Option<PlatformsImagesError> = serde_json::from_str(&content).ok();
        let error = ResponseContent { status, content, entity };
        Err(Error::ResponseError(error))
    }
}

