/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevelopersAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::DevelopersAllOfData,
}

impl DevelopersAllOf {
    pub fn new(data: crate::models::DevelopersAllOfData) -> DevelopersAllOf {
        DevelopersAllOf {
            data,
        }
    }
}


