/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DevelopersAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "developers")]
    pub developers: ::std::collections::HashMap<String, crate::models::Developer>,
}

impl DevelopersAllOfData {
    pub fn new(count: i32, developers: ::std::collections::HashMap<String, crate::models::Developer>) -> DevelopersAllOfData {
        DevelopersAllOfData {
            count,
            developers,
        }
    }
}


