/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesByGameIdV1AllOf {
    #[serde(rename = "data")]
    pub data: crate::models::GamesByGameIdAllOfData,
    #[serde(rename = "include")]
    pub include: crate::models::GamesByGameIdV1AllOfInclude,
}

impl GamesByGameIdV1AllOf {
    pub fn new(data: crate::models::GamesByGameIdAllOfData, include: crate::models::GamesByGameIdV1AllOfInclude) -> GamesByGameIdV1AllOf {
        GamesByGameIdV1AllOf {
            data,
            include,
        }
    }
}


