/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesByGameIdAllOfIncludeBoxart {
    #[serde(rename = "base_url")]
    pub base_url: crate::models::ImageBaseUrlMeta,
    #[serde(rename = "data")]
    pub data: ::std::collections::HashMap<String, Vec<crate::models::GameImage>>,
}

impl GamesByGameIdAllOfIncludeBoxart {
    pub fn new(base_url: crate::models::ImageBaseUrlMeta, data: ::std::collections::HashMap<String, Vec<crate::models::GameImage>>) -> GamesByGameIdAllOfIncludeBoxart {
        GamesByGameIdAllOfIncludeBoxart {
            base_url,
            data,
        }
    }
}


