/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesImagesAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::GamesImagesAllOfData,
}

impl GamesImagesAllOf {
    pub fn new(data: crate::models::GamesImagesAllOfData) -> GamesImagesAllOf {
        GamesImagesAllOf {
            data,
        }
    }
}


