/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesByGameIdAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "games")]
    pub games: Vec<crate::models::Game>,
}

impl GamesByGameIdAllOfData {
    pub fn new(count: i32, games: Vec<crate::models::Game>) -> GamesByGameIdAllOfData {
        GamesByGameIdAllOfData {
            count,
            games,
        }
    }
}


