/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesByGameIdAllOfIncludePlatform {
    #[serde(rename = "data")]
    pub data: ::std::collections::HashMap<String, crate::models::PlatformSkinny>,
}

impl GamesByGameIdAllOfIncludePlatform {
    pub fn new(data: ::std::collections::HashMap<String, crate::models::PlatformSkinny>) -> GamesByGameIdAllOfIncludePlatform {
        GamesByGameIdAllOfIncludePlatform {
            data,
        }
    }
}


