/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesByGameIdAllOfInclude {
    #[serde(rename = "boxart")]
    pub boxart: crate::models::GamesByGameIdAllOfIncludeBoxart,
    #[serde(rename = "platform")]
    pub platform: crate::models::GamesByGameIdAllOfIncludePlatform,
}

impl GamesByGameIdAllOfInclude {
    pub fn new(boxart: crate::models::GamesByGameIdAllOfIncludeBoxart, platform: crate::models::GamesByGameIdAllOfIncludePlatform) -> GamesByGameIdAllOfInclude {
        GamesByGameIdAllOfInclude {
            boxart,
            platform,
        }
    }
}


