/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenresAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "genres")]
    pub genres: ::std::collections::HashMap<String, crate::models::Genre>,
}

impl GenresAllOfData {
    pub fn new(count: i32, genres: ::std::collections::HashMap<String, crate::models::Genre>) -> GenresAllOfData {
        GenresAllOfData {
            count,
            genres,
        }
    }
}


