/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenresAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::GenresAllOfData,
}

impl GenresAllOf {
    pub fn new(data: crate::models::GenresAllOfData) -> GenresAllOf {
        GenresAllOf {
            data,
        }
    }
}


