/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedApiResponseAllOf {
    #[serde(rename = "pages")]
    pub pages: crate::models::PaginatedApiResponseAllOfPages,
}

impl PaginatedApiResponseAllOf {
    pub fn new(pages: crate::models::PaginatedApiResponseAllOfPages) -> PaginatedApiResponseAllOf {
        PaginatedApiResponseAllOf {
            pages,
        }
    }
}


