/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedApiResponseAllOfPages {
    #[serde(rename = "previous")]
    pub previous: Option<String>,
    #[serde(rename = "current")]
    pub current: String,
    #[serde(rename = "next")]
    pub next: Option<String>,
}

impl PaginatedApiResponseAllOfPages {
    pub fn new(previous: Option<String>, current: String, next: Option<String>) -> PaginatedApiResponseAllOfPages {
        PaginatedApiResponseAllOfPages {
            previous,
            current,
            next,
        }
    }
}


