/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedApiResponseAllOfPages {
    #[serde(rename = "previous")]
    pub previous: String,
    #[serde(rename = "current")]
    pub current: String,
    #[serde(rename = "next")]
    pub next: String,
}

impl PaginatedApiResponseAllOfPages {
    pub fn new(previous: String, current: String, next: String) -> PaginatedApiResponseAllOfPages {
        PaginatedApiResponseAllOfPages {
            previous,
            current,
            next,
        }
    }
}


