/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedApiResponseAllOfPages {
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<String>,
    #[serde(rename = "current")]
    pub current: String,
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
}

impl PaginatedApiResponseAllOfPages {
    pub fn new(current: String) -> PaginatedApiResponseAllOfPages {
        PaginatedApiResponseAllOfPages {
            previous: None,
            current,
            next: None,
        }
    }
}


