/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformsByPlatformNameAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "platforms")]
    pub platforms: Vec<crate::models::Platform>,
}

impl PlatformsByPlatformNameAllOfData {
    pub fn new(count: i32, platforms: Vec<crate::models::Platform>) -> PlatformsByPlatformNameAllOfData {
        PlatformsByPlatformNameAllOfData {
            count,
            platforms,
        }
    }
}


