/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformsAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "platforms")]
    pub platforms: ::std::collections::HashMap<String, crate::models::Platform>,
}

impl PlatformsAllOfData {
    pub fn new(count: i32, platforms: ::std::collections::HashMap<String, crate::models::Platform>) -> PlatformsAllOfData {
        PlatformsAllOfData {
            count,
            platforms,
        }
    }
}


