/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Platform {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "alias")]
    pub alias: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "console")]
    pub console: String,
    #[serde(rename = "controller")]
    pub controller: String,
    #[serde(rename = "developer")]
    pub developer: String,
    #[serde(rename = "overview", skip_serializing_if = "Option::is_none")]
    pub overview: Option<String>,
}

impl Platform {
    pub fn new(id: i32, name: String, alias: String, icon: String, console: String, controller: String, developer: String) -> Platform {
        Platform {
            id,
            name,
            alias,
            icon,
            console,
            controller,
            developer,
            overview: None,
        }
    }
}


