/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformsAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::PlatformsAllOfData,
}

impl PlatformsAllOf {
    pub fn new(data: crate::models::PlatformsAllOfData) -> PlatformsAllOf {
        PlatformsAllOf {
            data,
        }
    }
}


