/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformsImagesAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "base_url")]
    pub base_url: crate::models::ImageBaseUrlMeta,
    #[serde(rename = "images")]
    pub images: ::std::collections::HashMap<String, Vec<crate::models::PlatformImage>>,
}

impl PlatformsImagesAllOfData {
    pub fn new(count: i32, base_url: crate::models::ImageBaseUrlMeta, images: ::std::collections::HashMap<String, Vec<crate::models::PlatformImage>>) -> PlatformsImagesAllOfData {
        PlatformsImagesAllOfData {
            count,
            base_url,
            images,
        }
    }
}


