/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformsByPlatformNameAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::PlatformsByPlatformNameAllOfData,
}

impl PlatformsByPlatformNameAllOf {
    pub fn new(data: crate::models::PlatformsByPlatformNameAllOfData) -> PlatformsByPlatformNameAllOf {
        PlatformsByPlatformNameAllOf {
            data,
        }
    }
}


