/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlatformsImagesAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::PlatformsImagesAllOfData,
}

impl PlatformsImagesAllOf {
    pub fn new(data: crate::models::PlatformsImagesAllOfData) -> PlatformsImagesAllOf {
        PlatformsImagesAllOf {
            data,
        }
    }
}


