/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishersAllOfData {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "publishers")]
    pub publishers: ::std::collections::HashMap<String, crate::models::Publisher>,
}

impl PublishersAllOfData {
    pub fn new(count: i32, publishers: ::std::collections::HashMap<String, crate::models::Publisher>) -> PublishersAllOfData {
        PublishersAllOfData {
            count,
            publishers,
        }
    }
}


