/*
 * TheGamesDB API
 *
 * API Documentation
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublishersAllOf {
    #[serde(rename = "data")]
    pub data: crate::models::PublishersAllOfData,
}

impl PublishersAllOf {
    pub fn new(data: crate::models::PublishersAllOfData) -> PublishersAllOf {
        PublishersAllOf {
            data,
        }
    }
}


